# Generated by Django 3.1.5 on 2021-11-09 09:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bankapp', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Transfer',
        ),
    ]
