# Generated by Django 3.1.5 on 2021-11-10 09:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('bankapp', '0002_delete_transfer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accountdetail',
            name='account_holder',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
