# Generated by Django 3.1.5 on 2021-11-10 10:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('bankapp', '0003_auto_20211110_1019'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accountdetail',
            name='account_holder',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
